title: Media Object
label: Media Object
status: alpha
context:
  component-type: block

  media_object__title: "BioSamples"
  media_object__text: "A database describing biological samples and providing links to associated experimental data."
  media_object__image_size: 64
variants:
  - name: reverse
    context:
      modifier_class: vf-media-object--reverse
  - name: with image
    context:
      media_object__image: https://www.ebi.ac.uk/biosamples/images/logo_biosamples.png
      media_object__image_alt: an icon
  - name: reverse with image
    context:
      modifier_class: vf-media-object--reverse
      media_object__image: https://www.ebi.ac.uk/biosamples/images/logo_biosamples.png
      media_object__image_alt: an icon
