title: Navigation
label: Navigation

status: live

context:
  component-type: block
  navigation:
    - text: Home
      navigation_href: https://example.com
    - text: Download
      navigation_href: https://example.com
    - text: Release Notes
      navigation_href: https://example.com
    - text: FAQ
      navigation_href: https://example.com
    - text: Help
      navigation_href: https://example.com
    - text: Licence
      navigation_href: https://example.com
    - text: About
      navigation_href: https://example.com
    - text: Feedback
      navigation_href: https://example.com

variants:
  - name: default
    hidden: true

  - name: global
    context:
      classModifier: global
      navigation:
        - text: services
          navigation_href: https://example.com
        - text: research
          navigation_href: https://example.com
        - text: training
          navigation_href: https://example.com
        - text: about us
          navigation_href: https://example.com

  - name: main
    context:
      classModifier: main
  - name: main-easy
    context:
      classModifier: main
      global_layout: easy
  - name: main-normal
    context:
      classModifier: main
      global_layout: normal
  - name: main-medium
    context:
      classModifier: main
      global_layout: medium
  - name: main-hard
    context:
      classModifier: main
      global_layout: hard
      global_theme: primary
  - name: main-extreme
    context:
      classModifier: main
      global_layout: extreme


  - name: additional
    context:
      heading: European Bioinformatics Institute
      classModifier: additional
      title: European Bioinformatics Institute
      navigation:
        - text: services
          navigation_href: https://example.com
        - text: research
          navigation_href: https://example.com
        - text: training
          navigation_href: https://example.com
        - text: about us
          navigation_href: https://example.com
