title: Summary
label: Summary
status: live
context:
  component-type: block

  summary__title: What is Cancer?
  summary__text: Cancer is a group of diseases involving abnormal cell growth with the potential to invade or spread to other parts of the body.
  summary__href: 'JavaScript:Void(0);'
variants:
  - name: article
    context:
      summary__variant_class: vf-summary--article
      summary__title: EMBL's top social media posts of 2017 and what we learned from them
      summary_date: 06 February 2018
      summary__text: I want to take a look back at my first full year as EMBL's social media manager. So what worked best over 2017 and what can I learn from this? My basic goals for VF’s social media are to build community and develop a shared understanding of who we as an organisation are. Consequently, I care about what resonates on the different social sites much more than driving traffic back to Visual Framework websites, although traffic is obviously a by-product.
      summary__comment_href: 'JavaScript:Void(0);'
      summary__comment_text: Leave Comment
      summary__author_href: 'JavaScript:Void(0);'
      summary__author_text: Laura Howes
  - name: news
    context:
      summary__variant_class: vf-summary--news
      summary__date: 03/09/1978
      summary__title: What is Cancer?
      summary__category: General
      summary__text: Combinations of cancer drugs can be quickly and cheaply tested using a novel microfluidic device.
  - name: news-has-image
    context:
      summary__variant_class: vf-summary--news
      summary__date: 03/09/1978
      summary__image: /assets/vf-summary/assets/vf-summary--news-has-image.jpg
      summary__title: What is Cancer?
      summary__category: General
      summary__text: Combinations of cancer drugs can be quickly and cheaply tested using a novel microfluidic device.
  - name: profile
    context:
      summary__variant_class: vf-summary--profile
      summary__image: /assets/vf-summary/assets/vf-icon--avatar.svg
      summary__email: contact@persons.com
      summary__phone: +49 6221 387 8443
      summary__mobile: +49 1758 991 179
      summary__title: Contact Name
      summary__text: EMBL Press Office
      summary__uuid: 0000 - 1234 - 4326 - XX03
  - name: large
    context:
      summary__variant_class: vf-summary--profile
      summary__modifier_class: vf-summary--profile-l
      summary__image: /assets/vf-summary/assets/vf-icon--avatar.svg
      summary__email: contact@persons.com
      summary__phone: +49 6221 387 8443
      summary__mobile: +49 1758 991 179
      summary__title: Contact Name
      summary__text: EMBL Press Office
      summary__uuid: 0000 - 1234 - 4326 - XX03
  - name: regular
    context:
      summary__variant_class: vf-summary--profile
      summary__modifier_class: vf-summary--profile-r
      summary__image: /assets/vf-summary/assets/vf-icon--avatar.svg
      summary__email: contact@persons.com
      summary__phone: +49 6221 387 8443
      summary__mobile: +49 1758 991 179
      summary__title: Contact Name
      summary__text: EMBL Press Office
      summary__uuid: 0000 - 1234 - 4326 - XX03
  - name: small
    context:
      summary__variant_class: vf-summary--profile
      summary__modifier_class: vf-summary--profile-s
      summary__image: /assets/vf-summary/assets/vf-icon--avatar.svg
      summary__email: contact@persons.com
      summary__title: Contact Name
      summary__text: EMBL Press Office
  - name: media
    context:
      summary__variant_class: vf-summary--media
      summary__title: BioSamples
      summary__text: A database describing biological samples and providing links to associated experimental data.
      summary__image: https://www.ebi.ac.uk/biosamples/images/logo_biosamples.png
  - name: media no image
    context:
      summary__variant_class: vf-summary--media
      summary__title: BioSamples
      summary__text: A database describing biological samples and providing links to associated experimental data.
  - name: publication
    context:
      summary__title: "Computer modeling in developmental biology: growing today, essential tomorrow."
      summary__author_text: "Jimenez RC, Albar JP, Bhak J, Blatter MC, Blicher T, Brazas MD, Brooksbank C, Budd A, De Las Rivas J, Dreyer J, van Driel MA, Dunn MJ, Fernandes PL, van Gelder CW, Hermjakob H, Ioannidis V, Judge DP, Kahlem P, Korpelainen E, Kraus HJ, Loveland J, Mayer C, McDowall J, Moran F, Mulder N, Nyronen T, Rother K, Salazar GA, Schneider R, Via A, Villaveces JM, Yu P, Schneider MV, Attwood TK, Corpas M."
      summary__source: The Journal of cell biology
      summary__date: 2019
      summary__text: "144(23):4214-4225. doi: 10.1242/dev.151274."
      summary__linkA: Europe
      summary__linkA_href: 'JavaScript:Void(0);'
      summary__linkB: PMC
      summary__linkB_href: 'JavaScript:Void(0);'
  - name: job
    context:
      summary__department: Science Faculty
      summary__department_href: 'JavaScript:Void(0);'
      summary__location: Heidelberg
      summary__location_href: 'JavaScript:Void(0);'
      summary__title: Group Leader - Cell and Biophysics
      summary__text: We are seeking to recruit outstanding group leaders who wish to carry out cutting-edge molecular cell biology research and/or technology development.
      summary__date: Posted 11th August 2018
      summary__days_left: in 8
