title: Breadcrumbs
label: Breadcrumbs
status: live
context:
  component-type: block
  breadcrumbs:
    - text: Explore
      breadcrumb_href: https://example.com
    - text: Topics
      breadcrumb_href: https://example.com
    - text: Centre
  related:
    - text: Biscuits
      breadcrumb_href: https://example.com
    - text: Fruits For Cheese
      breadcrumb_href: https://example.com
