title: Breadcrumbs
label: Breadcrumbs
status: live
context:
  component-type: block
  breadcrumbs:
    - text: Explore
      breadcrumb_href: javascript:void(0);
    - text: Topics
      breadcrumb_href: javascript:void(0);
    - text: Centre
  related:
    - text: Biscuits
      breadcrumb_href: javascript:void(0);
    - text: Fruits For Cheese
      breadcrumb_href: javascript:void(0);
