title: Masthead
label: Masthead
preview: '@preview--nogrid'
status: live

context:
  component-type: block

  masthead_href: 'JavaScript:Void(0);'

variants:
  - name: default
  - name: primary
    context:
      Primary: true
  - name: secondary
    context:
      Secondary: true
  - name: tertiary
    context:
      Tertiary: true

  - name: title block
    context:
      hasTitleBlock: true

  - name: title block (primary)
    context:
      hasTitleBlock: true
      Primary: true

  - name: image
    context:
      mastheadImageClass: true
      mastheadImage: "http://localhost:3003/vf-core/assets/vf-masthead/assets/group-bg_2d4155.png"

  - name: title block and image
    context:
      mastheadImageClass: true
      mastheadImage: "http://localhost:3003/vf-core/assets/vf-masthead/assets/group-bg_2d4155.png"
      hasTitleBlock: true

