title: Masthead
label: Masthead
preview: '@preview--nogrid'
status: live

context:
  component-type: block

  masthead_href: 'JavaScript:Void(0);'

variants:
  - name: default
  - name: primary
    context:
      Primary: true
  - name: secondary
    context:
      Secondary: true
  - name: tertiary
    context:
      Tertiary: true

  - name: title block
    context:
      hasTitleBlock: true
  - name: title block (primary)
    context:
      hasTitleBlock: true
      Primary: true

  - name: title block and image
    context:
      mastheadImageClass: true
      mastheadImage: "https://wwwdev.ebi.ac.uk/about/teams/web-development/wp-content/uploads/2019/12/pexels-photo-270348-1224x348.jpeg"
      hasTitleBlock: true
