title: Masthead
label: Masthead
preview: '@preview--nogrid'
status: live

context:
  component-type: block

  masthead_href: 'https://example.com'

  seacrch_example_href_1: 'https://example.com'
  seacrch_example_href_2: 'https://example.com'
  seacrch_example_href_3: 'https://example.com'
