title: Masthead
label: Masthead
preview: '@preview--nogrid'
status: live

context:
  component-type: block

  masthead_href: 'JavaScript:Void(0);'

variants:
  - name: default
  - name: primary
    context:
      mastheadThemeVariant: vf-masthead-theme--primary
  - name: secondary
    context:
      mastheadThemeVariant: vf-masthead-theme--secondary
  - name: tertiary
    context:
      mastheadThemeVariant: vf-masthead-theme--tertiary

  - name: title block
    context:
      hasTitleBlock: vf-masthead--with-title-block
  - name: title block (primary)
    context:
      hasTitleBlock: vf-masthead--with-title-block
      mastheadThemeVariant: vf-masthead-theme--primary

  - name: title block and image
    context:
      mastheadImageClass: vf-masthead--has-image
      mastheadImage: "https://wwwdev.ebi.ac.uk/about/teams/web-development/wp-content/uploads/2019/12/pexels-photo-270348-1224x348.jpeg"
      hasTitleBlock: vf-masthead--with-title-block
