title: Activity List
label: Activity List
status: alpha

context:
  component-type: block
  date: Tuesday 20th February 2018
  list:
    - <strong>Sonia Furtado Neves</strong> published <a href="https://example.com">'The Future of Training'</a> on <a href="https://example.com">EMBL News</a>.
    - <strong>Sonia Furtado Neves</strong> published <a href="https://example.com">'The Future of Training'</a> on <a href="https://example.com">EMBL News</a>.
    - <strong>Mark Boulton</strong> updated <a href="https://example.com">Digital Strategy</a> on <a href="https://example.com">Gitlab</a> to version 1.1, with the comment <blockquote class="vf-activity__blockquote | vf-blockquote">Additional detail added to social section.</blockquote>
