# The title shown on the component page
title: Hero
# Label shown on index pages
label: Hero
status: alpha
preview: "@preview--nogrid"
# The template used from /components/_previews
#
# Per-variant options
# variants:
# - name: default
#   hidden: true
context:
  component-type: container

  vf_hero_subheading: an example of some ancillary text
  vf_hero_text:
    - The Hentze group combines biochemical and <a href="JavaScript:Void(0);">systems–level approaches</a> to investigate the connections between <a href="JavaScript:Void(0);">gene expression</a> and <a href="JavaScript:Void(0);">cell metabolism</a>, and their roles in human disease.
  vf_hero_link_text: Learn more.
  vf_hero_heading: About the Hentze group!
variants:
  - name: default
    hidden: false
    context:
      spacing: 1200
      newTheme: primary
      vf_hero_image_size: auto 28.5rem
  - name: default with inline link
    hidden: false
    context:
      newTheme: primary
      spacing: 1200
      vf_hero_text: Learn more.
      vf_hero_href: JavaScript:Void(0);
  - name: default with image
    hidden: false
    context:
      newTheme: primary
      spacing: 1200
      vf_hero_image: url('https://acxngcvroo.cloudimg.io/v7/https://www.embl.org/files/wp-content/uploads/vf-hero-intense.png');

  - name: default with image and inline link
    hidden: false
    context:
      newTheme: primary
      spacing: 1200
      vf_hero_image: url('https://acxngcvroo.cloudimg.io/v7/https://www.embl.org/files/wp-content/uploads/vf-hero-intense.png');
      vf_hero_text: Learn more.
      vf_hero_href: JavaScript:Void(0);

  - name: spacing (800)
    context:
      spacing: 800
  - name: spacing (1200)
    context:
      spacing: 1200
  - name: spacing (1600)
    context:
      spacing: 1600
  - name: primary
    hidden: true
    context:
      newTheme: primary
  - name: secondary
    hidden: true
    context:
      newTheme: secondary
  - name: tertiary
    hidden: true
    context:
      newTheme: tertiary


